version: '3.7'

services: 
  mongo:
    image: mongo
    expose: ['27017']
#   ports:
#   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: crud-nodejs
    networks: 
    - training
    volumes: 
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # Este arquivo .JS cria o banco de dados junto ao usuário.

  express:
    image: mongo-express
    ports: 
    - "81:8081"
    depends_on: 
    - mongo
    environment: 
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    networks: 
    - training

  crud:
    build: .
    ports:
    - "82:4100"
    depends_on: 
    - mongo
    networks: 
    - training

networks: 
  training: