version: '3.7'

services: 
  mongo:
    image: mongo:latest
    expose: ['27017']
    environment:
      MONGO_INITDB_DATABASE: crud-nodejs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks: 
    - training

  express:
    image: mongo-express
    ports: 
    - "81:8081"
    depends_on: 
    - mongo
    environment: 
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    networks: 
    - training

  crud:
    build: .
    ports:
    - "82:4100"
    depends_on: 
    - mongo
    networks: 
    - training

networks: 
  training: